from __future__ import annotations

DV_GRAPH_VERSION = "v1.0-dv-langgraph"
DV_GRAPH_DESCRIPTION = "数字乡村 LangGraph 多 Agent 政策服务状态图"

DV_AGENT_NODE_DEFINITIONS = [
    {
        "id": "intent",
        "label": "IntentAgent",
        "type": "reasoning",
        "description": "识别用户意图：政策问答、办事引导、智慧农业诊断或通用咨询。",
        "input_keys": ["question"],
        "output_keys": ["intent", "intent_analysis"],
    },
    {
        "id": "case",
        "label": "CaseAgent",
        "type": "reasoning",
        "description": "识别具体事项类型（农机补贴、合作社办理、返乡创业等）并创建服务事项。",
        "input_keys": ["question", "intent"],
        "output_keys": ["case_type", "case_id"],
    },
    {
        "id": "slot",
        "label": "SlotAgent",
        "type": "memory",
        "description": "抽取用户条件（地区、主体类型、已有材料等），识别缺失信息。",
        "input_keys": ["question", "case_id"],
        "output_keys": ["extracted_slots", "missing_slots"],
    },
    {
        "id": "retrieval",
        "label": "RetrievalAgent",
        "type": "retrieval",
        "description": "构造检索 query，调用 LlamaIndex RAG 混合检索数字乡村政策库。",
        "input_keys": ["question", "case_type", "intent"],
        "output_keys": ["retrieval_query", "retrieved_chunks"],
    },
    {
        "id": "evidence",
        "label": "EvidenceAgent",
        "type": "reasoning",
        "description": "整理政策依据、补贴标准、有效期和适用范围。",
        "input_keys": ["retrieved_chunks"],
        "output_keys": ["evidence_summary", "citations"],
    },
    {
        "id": "followup",
        "label": "FollowupAgent",
        "type": "reasoning",
        "description": "根据缺失条件生成追问，避免信息不足时下结论。",
        "input_keys": ["missing_slots"],
        "output_keys": ["follow_up_questions"],
    },
    {
        "id": "eligibility",
        "label": "EligibilityAgent",
        "type": "reasoning",
        "description": "基于用户条件和政策依据生成资格初判（是否符合补贴/贷款/项目条件）。",
        "input_keys": ["extracted_slots", "retrieved_chunks"],
        "output_keys": ["eligibility_result"],
    },
    {
        "id": "workflow",
        "label": "WorkflowAgent",
        "type": "planning",
        "description": "抽取办事材料清单、办理流程步骤和对接部门。",
        "input_keys": ["retrieved_chunks", "case_type"],
        "output_keys": ["material_list", "workflow_steps"],
    },
    {
        "id": "agriculture",
        "label": "AgricultureAgent",
        "type": "reasoning",
        "description": "智慧农业场景分析：问题诊断、数字化方案、项目价值评估。",
        "input_keys": ["question", "intent", "retrieved_chunks"],
        "output_keys": ["agriculture_diagnosis"],
    },
    {
        "id": "risk",
        "label": "RiskAgent",
        "type": "governance",
        "description": "校验政策时效性、地区差异、材料完整性和高影响事项风险。",
        "input_keys": ["retrieved_chunks", "missing_slots", "case_type"],
        "output_keys": ["risk"],
    },
    {
        "id": "answer",
        "label": "AnswerAgent",
        "type": "generation",
        "description": "调用 LLM 生成最终回答，区分政策依据和 AI 推断。",
        "input_keys": ["question", "retrieved_chunks", "agent_context"],
        "output_keys": ["final_answer", "policy_basis", "ai_inference"],
    },
    {
        "id": "memory_write",
        "label": "MemoryWriteAgent",
        "type": "memory",
        "description": "写入本轮运行结果摘要和高频问题统计。",
        "input_keys": ["final_answer", "intent", "case_type"],
        "output_keys": ["memory_updates"],
    },
]

DV_AGENT_EDGE_DEFINITIONS = [
    {"source": "start", "target": "intent", "condition": "always"},
    {"source": "intent", "target": "case", "condition": "always"},
    {"source": "case", "target": "slot", "condition": "always"},
    {"source": "slot", "target": "retrieval", "condition": "always"},
    {"source": "retrieval", "target": "evidence", "condition": "always"},
    {"source": "evidence", "target": "followup", "condition": "missing_slots"},
    {"source": "evidence", "target": "eligibility", "condition": "eligibility_check"},
    {"source": "evidence", "target": "workflow", "condition": "workflow_or_material"},
    {"source": "evidence", "target": "agriculture", "condition": "agriculture_diagnosis"},
    {"source": "evidence", "target": "risk", "condition": "general_qa"},
    {"source": "followup", "target": "risk", "condition": "always"},
    {"source": "eligibility", "target": "workflow", "condition": "always"},
    {"source": "workflow", "target": "risk", "condition": "always"},
    {"source": "agriculture", "target": "risk", "condition": "always"},
    {"source": "risk", "target": "answer", "condition": "always"},
    {"source": "answer", "target": "memory_write", "condition": "always"},
    {"source": "memory_write", "target": "end", "condition": "always"},
]
